[build]
  base    = "Proyecto_Software_desarrollo-"
  command = "npm ci && npm run build"
  publish = "dist"

# SPA redirect para Vue Router (evita 404 al refrescar /login, etc.)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
